version: '2'

services:
  nginx:
    container_name: nginx
    image: openresty/openresty:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  php:
    container_name: php
    build:
      context: ./php
    ports:
      - "8000:8000"
    volumes:
      - ./php/config:/unit
      - ./www:/var/www/html
#curl -X PUT -d @unit/start.json http://localhost:8000/config/
#curl http://localhost:8000/config/